[tool.poetry]
name = "cooli"
version = "0.1.0"
description = ""
authors = ["Robin Ruede <robin.ruede@philips.com>"]

[tool.poetry.dependencies]
python = "^3.6"
numpy = "^1.15"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
